name: Generate Profile Summary Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub profile summary cards
    env:
      PROFILE_SUMMARY_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN != '' && secrets.SUMMARY_GITHUB_TOKEN || github.token }}

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ env.PROFILE_SUMMARY_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 5.5
          EXCLUDE: ""
          AUTO_PUSH: true
